from crawler.facade import test

test()
'''

house data structure

{
    'id': 11366461,
    'user_id': 1266493, 
    'address': '新生南路三段19巷乾淨美寓環境..', 
    'type': '1', 
    'post_id': 11366461, 
    'regionid': 1, 
    'sectionid': 5, 
    'streetid': 25669, 'room': 0, 'area': 13,
    'price': '26,000',
    'storeprice': 0,
    'comment_total': 0,
    'comment_unread': 0,
    'comment_ltime': 0,
    'hasimg': 1,
    'kind': 2,
    'shape': 2,
    'houseage': 0,
    'posttime': '26天前',
    'updatetime': 1630400338,
    'refreshtime': 1630400338,
    'checkstatus': 1,
    'status': '',
    'closed': 0,
    'cases_id': '',
    'social_house': 0,
    'distance': 0,
    'search_name': '',
    'mainarea': None,
    'balcony_area': None,
    'groundarea': None,
    'linkman': '王雲五基金會',
    'housetype': 1,
    'street_name': '新生南路三段',
    'alley_name': '19巷',
    'lane_name': '',
    'addr_number_name': '8號',
    'kind_name_img': '獨立套房',
    'address_img': '乾淨美寓環境佳鄰近大安森林公園',
    'cases_name': '雲五大樓',
    'layout': '',
    'layout_str': '',
    'roomStr': '',
    'allfloor': 6,
    'floorInfo': '樓層：3/6',
    'floorStr': '3F/6F',
    'discountPriceStr': '',
    'houseimg': None,
    'cartplace': '',
    'space_type_str': '',
    'kind_name': '獨立套房',
    'photoNum': '8',
    'filename': 'https://hp1.591.com.tw/house/active/2021/07/28/162744254810382702_210x158.crop.jpg',
    'nick_name': '屋主 王雲五基金會',
    'role_name': '屋主',
    'new_img': '',
    'regionname': '台北市',
    'sectionname': '大安區',
    'icon_name': '出租',
    'icon_class': 'rent',
    'fulladdress': '新生南路三段19巷乾淨美寓環境佳鄰近大安森林公園',
    'unit': '元/月',
    'houseid': 11366461,
    'region_name': '台北市',
    'section_name': '大安區',
    'location': '大安區-新生南路三段19巷8號',
}
'''